Repository Hochfrequenz/ahb-tabellen, pull requests merged in 2024-12, with the labels that each got.

#324 ci(octopus): Fix Octopus Deployment Workflow
  .octopus/deployment_process.ocl
  pulumi/Pulumi.dev.yaml
Labels: CI/CD

#325 fix: constant mapping in getFormatName
  src/server/repository/ahb.ts
Labels: fix

#328 chore: add `Impressum` and `Datenschutz` hyperlinks to footer
  src/app/shared/components/footer/footer.component.html
Labels: chore

#330 ci(GH Action): Fill Version Endpoint with Information
  .github/workflows/deploy.yml
  Dockerfile
  src/server.ts
Labels: CI/CD

#331 fix: fix linebreak of collapsible conditions
  src/app/features/ahbs/components/ahb-table/ahb-table.component.html
  src/app/features/ahbs/components/ahb-table/ahb-table.component.ts
Labels: fix

#335 ci(octopus): Update Pulumi For Prod Environment
  .octopus/deployment_process.ocl
  .octopus/variables.ocl
Labels: CI/CD

#337 fix(auth0): Add new client id
  src/app/environments/environment.prod.ts
  src/app/environments/environment.ts
Labels: fix

#336 feat: add logput/login button to the ahb landingpage and the table view,
  src/app/features/ahbs/views/ahb-landing-page/ahb-landing-page.component.html
  src/app/features/ahbs/views/ahb-landing-page/ahb-landing-page.component.ts
  src/app/features/ahbs/views/ahb-page/ahb-page.component.html
  src/app/features/ahbs/views/ahb-page/ahb-page.component.ts
Labels: feature

#334 feat: Add Fallback component for an unknown prüfi.
  src/app/features/ahbs/views/ahb-page/ahb-page.component.html
  src/app/features/ahbs/views/ahb-page/ahb-page.component.ts
  src/app/shared/components/fallback-page/fallback-page.component.css
  src/app/shared/components/fallback-page/fallback-page.component.html
  src/app/shared/components/fallback-page/fallback-page.component.spec.ts
  src/app/shared/components/fallback-page/fallback-page.component.ts
Labels: feature

#339 ci(GH Action): use environment variables instead of outputs
  .github/workflows/deploy.yml
  docker-compose.yaml
Labels: CI/CD

#338 chore: skip authentication during local development
  src/app/app.config.ts
  src/app/environments/environment.interface.ts
  src/app/environments/environment.prod.ts
  src/app/environments/environment.ts
  src/app/features/landingpage/views/landing-page/landing-page.component.ts
  src/app/guards/auth.guard.ts
  src/app/shared/components/login-button/login-button.component.ts
Labels: chore

#340 fix(Dockerfile): Dockerfile To Get Build Information Into Version Endpoint
  Dockerfile
  docker-compose.yaml
Labels: fix

#341 fix: move auth button into header component
  src/app/features/ahbs/views/ahb-landing-page/ahb-landing-page.component.html
  src/app/features/ahbs/views/ahb-page/ahb-page.component.html
  src/app/features/landingpage/views/landing-page/landing-page.component.html
  src/app/shared/components/header/header.component.html
  src/app/shared/components/header/header.component.ts
Labels: fix

#343 ci(octopus): Accelerate Deployment Process
  CopyToTmp.sh
Labels: CI/CD
