Repository Hochfrequenz/ahb-tabellen, pull requests merged in 2025-09, with the labels that each got.

#651 fix: Refactor updateURL to simplify query parameter handling
  src/app/shared/components/input-search-enhanced/input-search-enhanced.component.ts
Labels: fix

#656 docs(changelog): Add git cliff to generate changelogs
  .gitattributes
  .github/CODEOWNERS
  .github/dependabot.yml
  .github/workflows/deploy.yml
  .prettierignore
  CHANGELOG.md
  README.md
  cliff.toml
Labels: documentation

#670 feat(tab-title): Updates page title with AHB description
  src/app/app.config.ts
  src/app/features/ahbs/views/ahb-landing-page/ahb-landing-page.component.ts
  src/app/features/ahbs/views/ahb-page/ahb-page.component.ts
  src/app/features/landingpage/views/landing-page/landing-page.component.ts
Labels: feature

#671 style: add Beschreibung to input field Prüfidentifikator
  src/app/features/ahbs/components/pruefi-input/pruefi-input.component.html
Labels: style

#672 chore(gh-action): sync task types with cliff commit parsers
  .github/workflows/conventional-commit-check.yml
Labels: chore
