Repository Hochfrequenz/ahb-tabellen, pull requests merged in 2025-01, with the labels that each got.

#357 ci(azure): increase startup time for container in azure
  pulumi/__main__.py
Labels: CI/CD

#358 ci(pulumi): set websitesContainerStartTimeLimit
  pulumi/Pulumi.dev.yaml
  pulumi/Pulumi.prod.yaml
Labels: CI/CD

#359 ci: add environment info to version endpoint
  src/server.ts
Labels: CI/CD

#360 ci: add clientid to version endpoint
  src/server.ts
  start.sh
Labels: CI/CD

#361 ci(stage): fix angular build command
  start.sh
Labels: CI/CD

#391 chore(design): make kohlrahbi in footer monospace font
  src/app/shared/components/footer/footer.component.html
  src/index.html
  tailwind.config.js
Labels: chore

#392 chore(design): Add logout icon and use mdi
  package-lock.json
  package.json
  src/app/shared/components/footer/footer.component.html
  src/app/shared/components/footer/footer.component.ts
  src/app/shared/components/icon-heart/icon-heart.component.ts
  src/app/shared/components/login-button/login-button.component.html
  src/styles.scss
Labels: chore

#390 refactor(api): Refactor interaction with blobstorage
  azure-mock/upload-documents.ts
  docker-compose.yaml
  src/app/core/api/api-configuration.ts
  src/app/core/api/api.module.ts
  src/app/core/api/base-service.ts
  src/app/core/api/models.ts
  src/app/core/api/models/ahb.ts
  src/app/core/api/models/format-version.ts
  src/app/core/api/models/version.ts
  src/app/core/api/services/ahb.service.ts
  src/app/core/api/services/maintenance.service.ts
  src/app/core/api/strict-http-response.ts
  src/app/shared/components/footer/footer.component.ts
  src/server.ts
  src/server/repository/formatVersion.ts
Labels: refactor

#400 fix: remove unused imports
  src/app/features/ahbs/views/ahb-landing-page/ahb-landing-page.component.ts
  src/app/features/ahbs/views/ahb-page/ahb-page.component.ts
  src/app/features/landingpage/views/landing-page/landing-page.component.ts
Labels: fix

#399 chore: adjust landing page text and remove justification
  src/app/features/landingpage/views/landing-page/landing-page.component.html
Labels: chore

#403 feat: add link to self (instead of just other solutions)
  src/app/shared/components/footer/footer.component.html
Labels: feature

#412 docs(CD): Add Deployment Section to README
  README.md
Labels: documentation

#416 refactor(get-ahblines): Get ahblines from sqlite instead from json files
  openapi.yml
  src/app/core/api/models/ahb.ts
  src/app/features/ahbs/views/ahb-page/test-data.ts
  src/server/entities/ahb-line.entity.ts
  src/server/infrastructure/database.ts
  src/server/repository/ahb.ts
Labels: refactor

#415 refactor(format-version-endpoint): Use sqlite data for the list of valid format versions
  bruno/Get FormatVersions.bru
  openapi.yml
  src/app/core/api/models/ahb.ts
  src/app/features/ahbs/views/ahb-page/test-data.ts
  src/server/entities/ahb-line.entity.ts
  src/server/infrastructure/database.ts
  src/server/repository/ahb.ts
  src/server/repository/formatVersion.ts
Labels: refactor

#414 refactor(pruefi-suggestion-dropdown): Add Suggestion Dropdown List For Pruefis With Name
  bruno/Get FormatVersions.bru
  openapi.yml
  src/app/core/api/models/ahb.ts
  src/app/features/ahbs/components/pruefi-input/pruefi-input.component.html
  src/app/features/ahbs/components/pruefi-input/pruefi-input.component.ts
  src/app/features/ahbs/views/ahb-page/test-data.ts
  src/server/entities/ahb-line.entity.ts
  src/server/infrastructure/database.ts
  src/server/repository/ahb.ts
  src/server/repository/formatVersion.ts
Labels: refactor

#420 chore: increase form elements' border radius and center components
  src/app/features/ahbs/components/ahb-search-form-header/ahb-search-form-header.component.html
  src/app/features/ahbs/components/format-version-select/format-version-select.component.html
  src/app/features/ahbs/components/pruefi-input/pruefi-input.component.html
Labels: chore
