Repository Hochfrequenz/ahb-tabellen, pull requests merged in 2025-03, with the labels that each got.

#502 ci: remove PAT references from workflows
  .github/workflows/deploy.yml
  .prettierignore
  package-lock.json
Labels: CI/CD

#491 style: Further Design Updates
  src/app/features/ahbs/components/ahb-table/ahb-table.component.html
  src/app/features/ahbs/views/ahb-page/ahb-page.component.html
  src/app/features/landingpage/views/landing-page/landing-page.component.html
Labels: style

#505 chore(version-endpoint): remove auth0 client id from version endpoint
  src/server.ts
Labels: chore

#512 style(footer): incease padding in y direction
  src/app/shared/components/footer/footer.component.html
Labels: style

#513 feat(refresh-token): use refresh token
  src/app/app.config.ts
Labels: feature
